### ISSUE TITLE
Bar icon doesn't appear in dark theme. (And resolution)

### ISSUE THREAD

**Issue by tioover** [nhojb/SyncthingBar#2]
<img width="428" alt="2017-08-27 6 41 26" src="https://user-images.githubusercontent.com/930060/29749101-58decc62-8b57-11e7-8a31-916c1ae334a6.png">
<img width="456" alt="2017-08-27 6 39 40" src="https://user-images.githubusercontent.com/930060/29749102-58e05c08-8b57-11e7-9764-b28650291094.png">

Simple revent:
 
![image 1](https://user-images.githubusercontent.com/930060/29749205-4d0ddca0-8b59-11e7-81f5-17f6c6b4e94d.png)
![image](https://user-images.githubusercontent.com/930060/29749206-5004448a-8b59-11e7-82e6-b6fc90467d59.png)

^ There are two white icon, select it

**Comment by r-chris** [comment]
Just in case you are interested - there is an older [alternative syncthing-bar](https://github.com/m0ppers/syncthing-bar) that supports dark theme, but I'm not sure who has more the features.

**Comment by xor-gate** [comment]
My synthing-macosx tray supports HiDPI and dark theme for the tray icon and is updated sometimes https://github.com/xor-gate/syncthing-macosx. It seems @nhojb doesn't active develop SyncthingBar.

**Comment by nhojb** [comment]
Just fixed this in v1.0.1 (available in the releases section). Apologies for the delay :-/
